export interface Track {
  id: string;
  title: string;
  artist: string;
  album: string;
  duration: number;
  bpm?: number;
  fileHash: string;
  filePath: string;
  fileSize: number;
  bitrate?: number;
}

export const mockTracks: Track[] = [
  {
    id: '1',
    title: 'Midnight Dreams',
    artist: 'Electronic Soul',
    album: 'Neon Nights',
    duration: 245,
    bpm: 128,
    fileHash: 'abc123def456',
    filePath: '/Music/Electronic Soul/Neon Nights/01 Midnight Dreams.mp3',
    fileSize: 7854321,
    bitrate: 320,
  },
  {
    id: '2',
    title: 'Sunset Boulevard',
    artist: 'Chillwave Collective',
    album: 'Summer Vibes',
    duration: 312,
    bpm: 110,
    fileHash: 'ghi789jkl012',
    filePath:
      '/Music/Chillwave Collective/Summer Vibes/03 Sunset Boulevard.mp3',
    fileSize: 9521000,
    bitrate: 320,
  },
  {
    id: '3',
    title: 'Digital Love',
    artist: 'Synthwave Dreams',
    album: 'Retro Future',
    duration: 198,
    bpm: 120,
    fileHash: 'mno345pqr678',
    filePath: '/Music/Synthwave Dreams/Retro Future/05 Digital Love.mp3',
    fileSize: 6215000,
    bitrate: 256,
  },
  {
    id: '4',
    title: 'Ocean Waves',
    artist: 'Ambient Masters',
    album: 'Nature Sounds',
    duration: 420,
    bpm: 60,
    fileHash: 'stu901vwx234',
    filePath: '/Music/Ambient Masters/Nature Sounds/02 Ocean Waves.mp3',
    fileSize: 12345000,
    bitrate: 320,
  },
  {
    id: '5',
    title: 'City Lights',
    artist: 'Urban Beats',
    album: 'Metropolitan',
    duration: 278,
    bpm: 135,
    fileHash: 'yzA567BCD890',
    filePath: '/Music/Urban Beats/Metropolitan/04 City Lights.mp3',
    fileSize: 8765000,
    bitrate: 320,
  },
  {
    id: '6',
    title: 'Forest Path',
    artist: 'Nature Harmony',
    album: 'Earth Elements',
    duration: 356,
    bpm: 85,
    fileHash: 'EFG123HIJ456',
    filePath: '/Music/Nature Harmony/Earth Elements/01 Forest Path.mp3',
    fileSize: 10567000,
    bitrate: 256,
  },
  {
    id: '7',
    title: 'Neon Rain',
    artist: 'Cyber Punk',
    album: 'Future City',
    duration: 245,
    bpm: 140,
    fileHash: 'KLM789NOP012',
    filePath: '/Music/Cyber Punk/Future City/03 Neon Rain.mp3',
    fileSize: 7234000,
    bitrate: 320,
  },
  {
    id: '8',
    title: 'Stellar Journey',
    artist: 'Space Odyssey',
    album: 'Galaxy Explorer',
    duration: 512,
    bpm: 95,
    fileHash: 'QRS345TUV678',
    filePath: '/Music/Space Odyssey/Galaxy Explorer/02 Stellar Journey.mp3',
    fileSize: 15789000,
    bitrate: 320,
  },
  {
    id: '9',
    title: 'Morning Coffee',
    artist: 'LoFi Lounge',
    album: 'Study Sessions',
    duration: 189,
    bpm: 75,
    fileHash: 'WXY901ZAB234',
    filePath: '/Music/LoFi Lounge/Study Sessions/06 Morning Coffee.mp3',
    fileSize: 5678000,
    bitrate: 256,
  },
  {
    id: '10',
    title: 'Thunderstorm',
    artist: 'Weather Moods',
    album: 'Nature Sounds',
    duration: 378,
    bpm: 70,
    fileHash: 'CDE567FGH890',
    filePath: '/Music/Weather Moods/Nature Sounds/04 Thunderstorm.mp3',
    fileSize: 11234000,
    bitrate: 320,
  },
  {
    id: '11',
    title: 'Dance Floor',
    artist: 'Club Nights',
    album: 'Party Mix',
    duration: 298,
    bpm: 128,
    fileHash: 'IJK123LMN456',
    filePath: '/Music/Club Nights/Party Mix/01 Dance Floor.mp3',
    fileSize: 9234000,
    bitrate: 320,
  },
  {
    id: '12',
    title: 'Mountain High',
    artist: 'Adventure Sounds',
    album: 'Epic Journeys',
    duration: 445,
    bpm: 80,
    fileHash: 'OPQ789RST012',
    filePath: '/Music/Adventure Sounds/Epic Journeys/05 Mountain High.mp3',
    fileSize: 13456000,
    bitrate: 320,
  },
  {
    id: '13',
    title: 'Jazz Cafe',
    artist: 'Smooth Jazz',
    album: 'Evening Relaxation',
    duration: 312,
    bpm: 90,
    fileHash: 'UVW345XYZ678',
    filePath: '/Music/Smooth Jazz/Evening Relaxation/02 Jazz Cafe.mp3',
    fileSize: 9678000,
    bitrate: 320,
  },
  {
    id: '14',
    title: 'Electric Pulse',
    artist: 'Techno Tribe',
    album: 'Digital Underground',
    duration: 267,
    bpm: 138,
    fileHash: 'ABC901DEF234',
    filePath: '/Music/Techno Tribe/Digital Underground/04 Electric Pulse.mp3',
    fileSize: 8123000,
    bitrate: 320,
  },
  {
    id: '15',
    title: 'River Flow',
    artist: 'Zen Garden',
    album: 'Meditation Guide',
    duration: 498,
    bpm: 65,
    fileHash: 'GHI567JKL890',
    filePath: '/Music/Zen Garden/Meditation Guide/01 River Flow.mp3',
    fileSize: 15234000,
    bitrate: 256,
  },
];
